In [1]:
%reset -f
import numpy as np
import tensorflow as tf
from numpy import array

In [2]:
# define input sequence
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([25, 45, 65, 85, 105, 125, 145, 165, 185])

In [3]:
# stack columns
dataset = np.vstack((in_seq1, in_seq2, out_seq)).T
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [4]:
# splt a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X,y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        
        # check if we are beyond the sequence
        if end_ix > len(sequence) -1:
            break
            
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix, :], sequence[end_ix, :]
        X.append(seq_x)
        y.append(seq_y)
        
    return array(X), array(y)

In [5]:
# choose a numbre of time steps
n_steps = 3

# split into sample
X, y  = split_sequence(dataset, n_steps)
print(X.shape, y.shape)

# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [6]:
# univariate lstm example
from tensorflow.keras import Input
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

# define model
n_features = 3
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = 'relu', return_sequences= True)(x0)
x2 = LSTM(50, activation = 'relu')(x1)
output = Dense(3)(x2)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = 'adam', loss = 'mse')

# fit the model
model.fit(X, y, epochs = 400, verbose = 1)

Epoch 1/400
1/1 [==============================] - 2s 2s/step - loss: 9517.1572
Epoch 2/400
1/1 [==============================] - 0s 8ms/step - loss: 9305.3115
Epoch 3/400
1/1 [==============================] - 0s 5ms/step - loss: 9141.8711
Epoch 4/400
1/1 [==============================] - 0s 6ms/step - loss: 9014.7969
Epoch 5/400
1/1 [==============================] - 0s 5ms/step - loss: 8900.1377
Epoch 6/400
1/1 [==============================] - 0s 6ms/step - loss: 8788.1611
Epoch 7/400
1/1 [==============================] - 0s 6ms/step - loss: 8675.6592
Epoch 8/400
1/1 [==============================] - 0s 6ms/step - loss: 8561.0029
Epoch 9/400
1/1 [==============================] - 0s 6ms/step - loss: 8438.9893
Epoch 10/400
1/1 [==============================] - 0s 6ms/step - loss: 8313.4932
Epoch 11/400
1/1 [==============================] - 0s 6ms/step - loss: 8179.1499
Epoch 12/400
1/1 [==============================] - 0s 6ms/step - loss: 8031.1094
Epoch 13/400
1/1 [========

1/1 [==============================] - 0s 8ms/step - loss: 0.1129
Epoch 103/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0724
Epoch 104/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0999
Epoch 105/400
1/1 [==============================] - 0s 10ms/step - loss: 0.1139
Epoch 106/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0914
Epoch 107/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0961
Epoch 108/400
1/1 [==============================] - 0s 10ms/step - loss: 0.1185
Epoch 109/400
1/1 [==============================] - 0s 10ms/step - loss: 0.1019
Epoch 110/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0756
Epoch 111/400
1/1 [==============================] - 0s 20ms/step - loss: 0.0784
Epoch 112/400
1/1 [==============================] - 0s 7ms/step - loss: 0.0769
Epoch 113/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0560
Epoch 114/400
1/1 [=============================

Epoch 204/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0050
Epoch 205/400
1/1 [==============================] - 0s 14ms/step - loss: 0.0049
Epoch 206/400
1/1 [==============================] - 0s 6ms/step - loss: 0.0048
Epoch 207/400
1/1 [==============================] - 0s 12ms/step - loss: 0.0047
Epoch 208/400
1/1 [==============================] - 0s 50ms/step - loss: 0.0047
Epoch 209/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0046
Epoch 210/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0045
Epoch 211/400
1/1 [==============================] - 0s 8ms/step - loss: 0.0045
Epoch 212/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0044
Epoch 213/400
1/1 [==============================] - 0s 8ms/step - loss: 0.0044
Epoch 214/400
1/1 [==============================] - 0s 13ms/step - loss: 0.0043
Epoch 215/400
1/1 [==============================] - 0s 14ms/step - loss: 0.0043
Epoch 216/400
1/1 [=============

1/1 [==============================] - 0s 8ms/step - loss: 0.0021
Epoch 306/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0021
Epoch 307/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0021
Epoch 308/400
1/1 [==============================] - 0s 19ms/step - loss: 0.0021
Epoch 309/400
1/1 [==============================] - 0s 8ms/step - loss: 0.0021
Epoch 310/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0021
Epoch 311/400
1/1 [==============================] - 0s 8ms/step - loss: 0.0020
Epoch 312/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0020
Epoch 313/400
1/1 [==============================] - 0s 8ms/step - loss: 0.0020
Epoch 314/400
1/1 [==============================] - 0s 11ms/step - loss: 0.0020
Epoch 315/400
1/1 [==============================] - 0s 9ms/step - loss: 0.0020
Epoch 316/400
1/1 [==============================] - 0s 10ms/step - loss: 0.0020
Epoch 317/400
1/1 [==============================

In [7]:
# demonstrate prediction
x_input = np.array([[70,75,145],[80,85,165],[90,95,185]])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[100.62762 105.63424 205.94293]]


In [8]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3, 3)]            0         
_________________________________________________________________
lstm (LSTM)                  (None, 3, 50)             10800     
_________________________________________________________________
lstm_1 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense (Dense)                (None, 3)                 153       
Total params: 31,153
Trainable params: 31,153
Non-trainable params: 0
_________________________________________________________________
